# Global Lima VM defaults - applies to ALL VMs
# This file is part of the dotfiles repo and gets symlinked to ~/.lima/_config/default.yaml

# Use Ubuntu LTS (not interim releases)
images:
  - location: "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-amd64.img"
    arch: "x86_64"
  - location: "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-arm64.img"
    arch: "aarch64"

provision:
  - mode: user
    script: |
      #!/bin/bash
      set -eux -o pipefail
      # Only run if dotfiles not already set up
      if [ ! -d "$HOME/.cfg" ]; then
        echo "Setting up dotfiles..."
        curl -Lks https://raw.githubusercontent.com/jimray/config/main/.dotfiles-init.sh -o /tmp/dotfiles-init.sh
        chmod +x /tmp/dotfiles-init.sh
        echo "y" | /tmp/dotfiles-init.sh
      else
        echo "Dotfiles already configured, skipping init"
      fi
