command_timeout=750

[cmd_duration]
disabled = true

[deno]
format = "[$symbol $version]($style) "
symbol = ""

[directory]
format = "[$path ]($style)"
truncate_to_repo = false
home_symbol = "󰥳 "

[git_branch]
symbol = " "
format = "([$symbol$branch]($style)) "

[git_status]
disabled = true

[golang]
symbol = " "

[hostname]
ssh_only = true
trim_at = "."
format = "@[$hostname]($style) "

[nodejs]
detect_extensions = []
symbol = ""
format = "[$symbol $version]($style)"

[package]
disabled = true

[python]
symbol = " "
format = "[${symbol}${pyenv_prefix}(${version} )]($style)"

[username]
format = "[$user]($style) "

