[deno]
format = "[$symbol $version]($style) "
symbol = ""

[directory]
format = "[$path ]($style)"
truncate_to_repo = false
home_symbol = "ﮟ "

[git_branch]
symbol = " "
format = "([$symbol$branch]($style)) "

[git_status]
disabled = true

[golang]
symbol = " "

[nodejs]
detect_extensions = []
symbol = ""
format = "[$symbol $version]($style)"

[package]
disabled = true

[python]
symbol = " "
format = "[${symbol}${pyenv_prefix}(${version} )]($style)"

